# Generated by Django 4.0.6 on 2022-07-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('license_number', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('last_seen', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
