# Generated by Django 4.0.6 on 2022-07-18 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_license_detect'),
    ]

    operations = [
        migrations.AddField(
            model_name='license_detect',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='license_detect',
            name='license_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.license'),
        ),
    ]
