# Generated by Django 4.0.6 on 2022-11-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_license_detect_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
